import type { Metadata } from "next";
import { Inter, Oswald, Caveat, Condiment } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
});

const condiment = Condiment({
  subsets: ["latin"],
  variable: "--font-condiment",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} ${caveat.variable} ${condiment.variable}`}
    >
      <body className="antialiased font-[var(--font-inter)]">
        <Header />
        {children}
      </body>
    </html>
  );
}
