import type { Metadata } from "next";
import { Inter, Oswald, Caveat, Condiment } from "next/font/google";
import ThemeProvider from "./ThemeProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Particles } from "@/components/ui/shadcn-io/particles";
import "./globals.css";
import "../CSS/ThemeSwitch.css";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
});

const condiment = Condiment({
  subsets: ["latin"],
  variable: "--font-condiment",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} ${caveat.variable} ${condiment.variable}`}
    >
      <body className="w-screen antialiased font-[var(--font-inter)] overflow-x-hidden">
        <Particles
          className={`fixed top-0 left-0 inset-0 w-full h-full light:bg-gradient-to-b light:from-[#F5F5F5] light:via-[#F7F7F7] light:to-[#F7F7F7]`}
          quantity={100}
          ease={80}
          staticity={50}
          color={`document.documentElement.classList.contains("light") ? "#FFFFFF : "#4B5563"`}
          size={0.8}
        />
        <ThemeProvider>
          <Header />

          {children}

          <Footer />
        </ThemeProvider>

        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.8.1/vanilla-tilt.min.js"
          strategy="afterInteractive"
          integrity="sha512-wC/cunGGDjXSl9OHUH0RuqSyW4YNLlsPwhcLxwWW1CR4OeC2E1xpcdZz2DeQkEmums41laI+eGMw95IJ15SS3g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </body>
    </html>
  );
}
